export const SUBTASK_STATUS = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED'
};

export const SUBTASK_STATUS_LABELS = {
  [SUBTASK_STATUS.PENDING]: '待处理',
  [SUBTASK_STATUS.PROCESSING]: '处理中',
  [SUBTASK_STATUS.COMPLETED]: '已完成'
};

