export const TOOL_TYPES = {
  PERMISSION: 'PERMISSION',
  DATA_EXTRACT: 'DATA_EXTRACT',
  DATA_FIX: 'DATA_FIX',
  CONSULT: 'CONSULT',
  OTHER: 'OTHER'
};

export const TOOL_TYPE_LABELS = {
  [TOOL_TYPES.PERMISSION]: '账号及权限申请',
  [TOOL_TYPES.DATA_EXTRACT]: '生产系统数据提取',
  [TOOL_TYPES.DATA_FIX]: '生产系统数据修正',
  [TOOL_TYPES.CONSULT]: '应用系统常规咨询',
  [TOOL_TYPES.OTHER]: '其他'
};

export const TOOL_TYPE_OPTIONS = [
  { label: TOOL_TYPE_LABELS[TOOL_TYPES.DATA_EXTRACT], value: TOOL_TYPES.DATA_EXTRACT },
  { label: TOOL_TYPE_LABELS[TOOL_TYPES.DATA_FIX], value: TOOL_TYPES.DATA_FIX },
  { label: TOOL_TYPE_LABELS[TOOL_TYPES.PERMISSION], value: TOOL_TYPES.PERMISSION },
  { label: TOOL_TYPE_LABELS[TOOL_TYPES.CONSULT], value: TOOL_TYPES.CONSULT }
];

export const L1_ACCEPTABLE_TOOL_TYPES = [
  TOOL_TYPES.DATA_EXTRACT,
  TOOL_TYPES.DATA_FIX,
  TOOL_TYPES.PERMISSION,
  TOOL_TYPES.CONSULT,
  TOOL_TYPES.OTHER
];
